# Generated by Django 4.1.7 on 2023-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("message", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
    ]
