# Generated by Django 4.1.7 on 2023-02-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmodel",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="logmodel", name="message", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="logmodel",
            name="time_end",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="logmodel",
            name="time_start",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
